INSERT INTO categories (name) VALUES 
('Accesorios para Vehículos'),
('Acc. para Motos y Cuatriciclos'),
('Acc. y Repuestos Náuticos'),
('Accesorios de Auto y Camioneta'),
('Accesorios para Camiones'),
('Audio para Vehículos'),
('Dispositivos para TelePASE'),
('GNC'),
('Herramientas'),
('Limpieza de Vehículos'),
('Llantas'),
('Navegadores GPS'),
('Neumáticos'),
('Performance'),
('Repuestos Autos y Camionetas'),
('Repuestos de Línea Pesada'),
('Repuestos Motos y Cuatriciclos'),
('Seguridad Vehicular'),
('Servicio Programado'),
('Tuning'),
('Otros'),
('Agro'),
('Animales'),
('Generadores de Energía'),
('Infraestructura Rural'),
('Insumos Agrícolas'),
('Insumos Ganaderos'),
('Máquinas y Herramientas'),
('Repuestos Maquinaria Agrícola'),
('Otros'),
('Alimentos y Bebidas'),
('Bebidas'),
('Comestibles'),
('Comida Preparada y Catering'),
('Congelados'),
('Frescos'),
('Otros'),
('Animales y Mascotas'),
('Aves'),
('Caballos'),
('Conejos'),
('Gatos'),
('Insectos'),
('Peces'),
('Perros'),
('Reptiles y Anfibios'),
('Roedores'),
('Otros'),
('Antigüedades y Colecciones'),
('Antigüedades'),
('Coleccionables de Deportes'),
('Esculturas'),
('Filatelia'),
('Militaría y Afines'),
('Monedas y Billetes'),
('Posters'),
('Otros'),
('Arte, Librería y Mercería'),
('Arte'),
('Espejos Venecitas'),
('Insumos para Hacer Velas'),
('Librería'),
('Mercería'),
('Moldes para Jabones'),
('Piezas para Llaveros'),
('Otros'),
('Autos, Motos y Otros'),
('Autos Chocados y Averiados'),
('Autos de Colección'),
('Autos y Camionetas'),
('Camiones'),
('Colectivos'),
('Maquinaria Agrícola'),
('Maquinaria Vial'),
('Motorhomes'),
('Motos'),
('Náutica'),
('Planes de Ahorro'),
('Semirremolques'),
('Otros Vehículos'),
('Bebés'),
('Andadores y Vehículos de Bebés'),
('Artículos de Bebés para Baño'),
('Artículos de Maternidad'),
('Chupetes y Mordillos'),
('Comida para Bebés'),
('Corralitos'),
('Cuarto del Bebé'),
('Higiene y Cuidado del Bebé'),
('Juegos y Juguetes para Bebés'),
('Lactancia y Alimentación'),
('Paseo del Bebé'),
('Ropa y Calzado para Bebés'),
('Salud del Bebé'),
('Seguridad para Bebés'),
('Otros'),
('Belleza y Cuidado Personal'),
('Artículos de Peluquería'),
('Barbería'),
('Cuidado de la Piel'),
('Cuidado del Cabello'),
('Depilación'),
('Electrodomésticos de Belleza'),
('Farmacia'),
('Higiene Personal'),
('Manicuría y Pedicuría'),
('Maquillaje'),
('Perfumes y Fragancias'),
('Tratamientos de Belleza'),
('Otros'),
('Cámaras y Accesorios'),
('Accesorios para Cámaras'),
('Álbumes y Portarretratos'),
('Cables'),
('Cámaras'),
('Drones y Accesorios'),
('Filmadoras y Cámaras de Acción'),
('Instrumentos Ópticos'),
('Lentes y Filtros'),
('Repuestos para Cámaras'),
('Revelado y Laboratorio'),
('Otros'),
('Celulares y Teléfonos'),
('Accesorios para Celulares'),
('Celulares y Smartphones'),
('Handies y Radiofrecuencia'),
('Lentes de Realidad Virtual'),
('Repuestos de Celulares'),
('Smartwatches y Accesorios'),
('Tarifadores y Cabinas'),
('Telefonía Fija e Inalámbrica'),
('Telefonía IP'),
('Otros'),
('Computación'),
('Accesorios de Antiestática'),
('Accesorios para PC Gaming'),
('Almacenamiento'),
('Cables y Hubs USB'),
('Cajas, Sobres y Porta CDs'),
('Componentes de PC'),
('Conectividad y Redes'),
('Estabilizadores y UPS'),
('Impresión'),
('Laptops y Accesorios'),
('Lectores y Scanners'),
('Limpieza y Cuidado de PCs'),
('Monitores y Accesorios'),
('Palms y Handhelds'),
('PC de Escritorio'),
('Periféricos de PC'),
('Proyectores y Pantallas'),
('Software'),
('Tablets y Accesorios'),
('Otros'),
('Consolas y Videojuegos'),
('Accesorios para Consolas'),
('Accesorios para PC Gaming'),
('Consolas'),
('Flippers y Arcade'),
('Repuestos para Consolas'),
('Videojuegos'),
('Otros'),
('Deportes y Fitness'),
('Artes Marciales y Boxeo'),
('Bádminton'),
('Básquet'),
('Buceo'),
('Camping, Caza y Pesca'),
('Canoas, Kayaks e Inflables'),
('Ciclismo'),
('Equitación y Polo'),
('Esgrima'),
('Esqui y Snowboard'),
('Fitness y Musculación'),
('Fútbol'),
('Fútbol Americano'),
('Golf'),
('Handball'),
('Hockey'),
('Juegos de Salón'),
('Kitesurf'),
('Monopatines y Scooters'),
('Montañismo y Trekking'),
('Natación'),
('Paintball'),
('Parapente'),
('Patín, Gimnasia y Danza'),
('Pilates y Yoga'),
('Pulsómetros y Cronómetros'),
('Ropa Deportiva'),
('Rugby'),
('Skateboard y Sandboard'),
('Slackline'),
('Softball y Beisbol'),
('Suplementos y Shakers'),
('Surf y Bodyboard'),
('Tenis, Padel y Squash'),
('Tiro Deportivo'),
('Voley'),
('Wakeboard y Esqui Acuático'),
('Windsurf'),
('Zapatillas'),
('Otros'),
('Electrodomésticos y Aires Ac.'),
('Artefactos de Cuidado Personal'),
('Climatización'),
('Cocción'),
('Dispensadores y Purificadores'),
('Lavado'),
('Pequeños Electrodomésticos'),
('Refrigeración'),
('Otros'),
('Electrónica, Audio y Video'),
('Accesorios para Audio y Video'),
('Accesorios para TV'),
('Audio'),
('Cables'),
('Componentes Electrónicos'),
('Controles Remotos'),
('Drones y Accesorios'),
('Fundas y Bolsos'),
('Media Streaming'),
('Pilas y Cargadores'),
('Proyectores y Pantallas'),
('Repuestos para TV'),
('Televisores'),
('Video'),
('Otros'),
('Entradas para Eventos'),
('Entradas de Colección'),
('Eventos a Beneficio'),
('Eventos Deportivos'),
('Exposiciones'),
('Recitales'),
('Teatro'),
('Otras Entradas'),
('Herramientas y Construcción'),
('Aberturas'),
('Baños y Sanitarios'),
('Construcción'),
('Electricidad'),
('Herramientas'),
('Mobiliario para Cocinas'),
('Pinturería'),
('Pisos y Revestimientos'),
('Plomería'),
('Otros'),
('Hogar, Muebles y Jardín'),
('Adornos y Decoración del Hogar'),
('Baños'),
('Bazar y Cocina'),
('Camas, Colchones y Accesorios'),
('Cuidado del Hogar y Lavandería'),
('Iluminación para el Hogar'),
('Jardin y Aire Libre'),
('Muebles para el Hogar'),
('Organización para el Hogar'),
('Seguridad para el Hogar'),
('Textiles de Hogar y Decoración'),
('Otros'),
('Industrias y Oficinas'),
('Arquitectura y Diseño'),
('Embalaje y Logística'),
('Equipamiento Médico'),
('Equipamiento para Comercios'),
('Equipamiento para Oficinas'),
('Gastronomía y Hotelería'),
('Gráfica e Impresión'),
('Herramientas Industriales'),
('Publicidad y Promoción'),
('Seguridad Laboral'),
('Textil y Calzado'),
('Uniformes'),
('Otros'),
('Inmuebles'),
('Camas Náuticas'),
('Campos'),
('Casas'),
('Cocheras'),
('Consultorios'),
('Departamentos'),
('Depósitos y Galpones'),
('Fondo de Comercio'),
('Locales'),
('Oficinas'),
('Parcelas, Nichos y Bóvedas'),
('PH'),
('Quintas'),
('Terrenos y Lotes'),
('Tiempo Compartido'),
('Otros Inmuebles'),
('Instrumentos Musicales'),
('Baterías y Percusión'),
('Equipos de DJ y Accesorios'),
('Estudio de Grabación'),
('Instrumentos de Cuerdas'),
('Instrumentos de Viento'),
('Metrónomos'),
('Micrófonos y Amplificadores'),
('Parlantes y Bafles'),
('Partituras y Letras'),
('Pedales y Accesorios'),
('Teclados y Pianos'),
('Otros'),
('Joyas y Relojes'),
('Exhibidores y Joyeros'),
('Insumos para Joyería'),
('Joyas y Bijouterie'),
('Piedras Preciosas'),
('Piercings'),
('Plumas y Lapiceras de Lujo'),
('Pulsómetros y Cronómetros'),
('Relojes'),
('Repuestos para Relojes'),
('Smartwatch'),
('Otros'),
('Juegos y Juguetes'),
('Armas y Lanzadores de Juguete'),
('Casas y Carpas para Niños'),
('Dibujo, Pintura y Manualidades'),
('Electrónicos para Niños'),
('Figuritas, Álbumes y Cromos'),
('Hobbies'),
('Instrumentos Musicales'),
('Juegos de Agua y Playa'),
('Juegos de Mesa y Cartas'),
('Juegos de Plaza y Aire Libre'),
('Juegos de Salón'),
('Juguetes Antiestrés e Ingenio'),
('Juguetes de Bromas'),
('Juguetes de Construcción'),
('Juguetes de Oficios'),
('Juguetes para Bebés'),
('Mesas y Sillas para Niños'),
('Muñecos y Muñecas'),
('Patines y Patinetas'),
('Peloteros y Castillos'),
('Peluches'),
('Títeres y Marionetas'),
('Vehículos de Juguete'),
('Vehículos Montables para Niños'),
('Otros'),
('Libros, Revistas y Comics'),
('Catálogos'),
('Comics e Historietas'),
('Libros'),
('Manga'),
('Revistas'),
('Otros'),
('Música, Películas y Series'),
('Cursos'),
('Música'),
('Películas'),
('Series de TV'),
('Otros'),
('Ropa y Accesorios'),
('Accesorios de Moda'),
('Bermudas y Shorts'),
('Blusas'),
('Buzos y Hoodies'),
('Calzado'),
('Calzas'),
('Camisas'),
('Camperas, Tapados y Trenchs'),
('Enteritos'),
('Equipaje, Bolsos y Carteras'),
('Lotes de Ropa'),
('Pantalones, Jeans y Joggings'),
('Polleras'),
('Remeras, Musculosas y Chombas'),
('Ropa de Danza y Patinaje'),
('Ropa Deportiva'),
('Ropa Interior y de Dormir'),
('Ropa y Calzado para Bebés'),
('Saquitos, Sweaters y Chalecos'),
('Trajes'),
('Trajes de Baño'),
('Uniformes y Ropa de Trabajo'),
('Vestidos'),
('Otros'),
('Salud y Equipamiento Médico'),
('Cuidado de la Salud'),
('Equipamiento Médico'),
('Masajes'),
('Movilidad'),
('Ortopedia'),
('Suplementos Alimenticios'),
('Terapias Alternativas'),
('Otros'),
('Servicios'),
('Asesoramiento Contable y Legal'),
('Belleza y Cuidado Personal'),
('Comunicación y diseño'),
('Cursos y Clases'),
('Delivery'),
('Fiestas y Eventos'),
('Fotografía, Música y Cine'),
('Hogar y Construcción'),
('Imprenta'),
('Mantenimiento de Vehículos'),
('Medicina y Salud'),
('Ropa y Moda'),
('Servicios para Mascotas'),
('Servicios para Oficinas'),
('Tecnología'),
('Transporte'),
('Viajes y Turismo'),
('Otros Servicios'),
('Souvenirs, Cotillón y Fiestas'),
('Cotillón'),
('Decoración para Fiestas'),
('Descartables para Fiestas'),
('Disfraces'),
('Espuma, Serpentina y Confeti'),
('Invitaciones y Tarjetas'),
('Kits Imprimibles para Fiestas'),
('Props para Photo Booths'),
('Souvenirs'),
('Otros'),
('Otras categorías'),
('Adultos'),
('Artículos para Fumadores'),
('Coberturas Extendidas'),
('Criptomonedas'),
('Esoterismo'),
('Gift Cards'),
('Hornos Crematorios'),
('Insumos para Tatuajes'),
('Kits de Criminalística'),
('Licencias para Taxis'),
('Mangas de Viento'),
('Pirotecnia'),
('Otros');



INSERT INTO brands (name) VALUES 
('Apple'),
('Amazon'),
('Google'),
('Microsoft'),
('Samsung Group'),
('Walmart'),
('Facebook'),
('ICBC'),
('Verizon'),
('WeChat'),
('China Construction Bank'),
('Toyota'),
('Mercedes-Benz'),
('Tencent'),
('Huawei'),
('State Grid'),
('Ping An'),
('Taobao'),
('Agricultural Bank Of China'),
('Home Depot'),
('AT&amp;T'),
('Disney'),
('Deutsche Telekom'),
('Tmall'),
('Bank of China'),
('Volkswagen'),
('Moutai'),
('Shell'),
('BMW'),
('Alibaba.com'),
('Starbucks'),
('China Mobile'),
('Saudi Aramco'),
('Mitsubishi Group'),
('Marlboro'),
('Porsche'),
('NTT Group'),
('McDonald\'s'),
('Coca-Cola'),
('Bank of America'),
('Citi'),
('Tesla'),
('Intel'),
('Wells Fargo'),
('PetroChina'),
('Honda'),
('Nike'),
('CSCEC'),
('Lowe\'s'),
('UPS'),
('Costco'),
('Chase'),
('IBM'),
('UnitedHealthcare'),
('CVS'),
('Deloitte'),
('VISA'),
('Sinopec'),
('Oracle'),
('accenture'),
('Wuliangye'),
('Xfinity'),
('Instagram'),
('Netflix'),
('Sumitomo Group'),
('JP Morgan'),
('American Express'),
('JD.com'),
('FedEx'),
('Hyundai Group'),
('Ford'),
('China Life'),
('Mitsui'),
('PWC'),
('Spectrum'),
('BP'),
('TATA Group'),
('SK Group'),
('China Merchants Bank'),
('Target'),
('Siemens Group'),
('Uber'),
('EY'),
('Allianz'),
('Evergrande'),
('Cisco'),
('Country Garden'),
('Nestle'),
('Vodafone'),
('Mastercard'),
('Orange'),
('LG Group'),
('Dell Technologies'),
('Bosch'),
('Pepsi'),
('Total'),
('General Electric'),
('SAP'),
('IKEA'),
('Volvo'),
('Axa'),
('YouTube'),
('Audi'),
('Vanke'),
('HSBC'),
('PayPal'),
('Nissan'),
('Walgreens'),
('Hitachi'),
('TD'),
('Chevron'),
('CRCC'),
('Anthem'),
('RBC'),
('Sony'),
('Bank of Communications'),
('GUCCI'),
('Aldi'),
('CPIC'),
('KFC'),
('Shanghai Pudong Development Bank'),
('CRECG'),
('Louis Vuitton'),
('au'),
('China CITIC Bank'),
('Adidas'),
('Santander'),
('AIA'),
('NetEase'),
('Goldman Sachs'),
('Chevrolet'),
('Boeing'),
('Postal Savings Bank'),
('ExxonMobil'),
('Humana'),
('China Telecom'),
('Chanel'),
('Salesforce'),
('ZARA'),
('UNIQLO'),
('Capital One'),
('SoftBank'),
('China Minsheng Bank'),
('Optum'),
('BNP Paribas'),
('H&amp;M'),
('TSMC'),
('KPMG'),
('MUFG'),
('Industrial Bank'),
('Cartier'),
('Petronas'),
('Enel'),
('JR'),
('Adobe'),
('Hermès'),
('Universal'),
('Lidl'),
('Greenland'),
('Longfor Properties'),
('GEICO'),
('Sam\'s Club'),
('ADNOC'),
('Johnson &amp; Johnson'),
('Lockheed Martin'),
('China Everbright Bank'),
('L\'Oréal'),
('Warner Bros'),
('Tesco'),
('ING'),
('Renault'),
('Sephora'),
('Panasonic'),
('Midea'),
('China Resources Land'),
('Dollar General'),
('Yili'),
('DHL'),
('Morgan Stanley'),
('Sber'),
('Nokia'),
('ENGIE'),
('Yahoo! Group'),
('Xiaomi'),
('Medtronic'),
('China Overseas Land &amp; Invest'),
('EDF'),
('Ferrari'),
('STC'),
('Purina'),
('Airbus'),
('7-Eleven'),
('Poly Real Estate'),
('BMO'),
('Scotiabank'),
('Barclays'),
('Sky'),
('Woolworths'),
('Progressive'),
('Equinor'),
('Lexus'),
('PICC'),
('Japan Post Holdings'),
('S&amp;P Global'),
('UBS'),
('LIC'),
('Gree'),
('Etisalat'),
('Eni'),
('NBC'),
('HP'),
('Infosys'),
('U.S. Bank'),
('eBay'),
('Metlife'),
('Brookfield'),
('Power China'),
('LinkedIn'),
('E.Leclerc'),
('booking.com'),
('Canon'),
('Danone'),
('Carrefour'),
('Subway'),
('Subaru'),
('Red Bull'),
('Reliance'),
('ESPN'),
('Nvidia'),
('Publix'),
('Cognizant'),
('Truist'),
('3M'),
('HCA'),
('Vinci'),
('Travelers'),
('Rolex'),
('China Unicom'),
('Caterpillar'),
('John Deere'),
('Movistar'),
('Dior'),
('Haier'),
('DBS'),
('Baidu'),
('Rakuten'),
('Zurich'),
('Roche'),
('Marubeni'),
('BBVA'),
('Fox'),
('BNSF'),
('Hilton'),
('Generali Group'),
('Rabobank'),
('Gillette'),
('Union Pacific'),
('Philips'),
('Sunac'),
('Intesa Sanpaolo'),
('BASF'),
('Chubb'),
('Bell'),
('Merrill'),
('Meituan'),
('Canada Life'),
('Pall Mall'),
('Yanghe'),
('CNBM'),
('SF Express'),
('Luzhou Laojiao'),
('Northrop Grumman'),
('Cigna'),
('Telenor'),
('CIBC'),
('Land Rover'),
('L&amp;M'),
('Allstate'),
('Michelin'),
('VMWARE'),
('Aviva'),
('Telstra'),
('Nippon Life Insurance'),
('Sherwin-Williams'),
('Bridgestone'),
('PNC'),
('CNOOC'),
('Pampers'),
('CRRC'),
('Capgemini'),
('Playstation'),
('Enterprise'),
('Kellogg\'s'),
('3'),
('HDFC Bank'),
('Aetna'),
('Lay\'s'),
('Commonwealth Bank'),
('Broadcom'),
('TJ Maxx'),
('Asda'),
('Mizuho Financial Group'),
('Kroger'),
('Gazprom'),
('Daiwa House'),
('Honeywell'),
('Activision Blizzard'),
('Tyson'),
('MCC'),
('Credit Suisse'),
('Telus'),
('Thermo Fisher Scientific'),
('Best Buy'),
('Youku'),
('Raytheon Technologies'),
('Poste Italiane'),
('Nivea'),
('Fubon Financial'),
('Hikvision'),
('El Corte Inglés'),
('QNB'),
('Domino\'s Pizza'),
('Airtel'),
('20th Television'),
('Viettel'),
('Standard Chartered'),
('TIM'),
('KEPCO'),
('Nescafé'),
('Bouygues'),
('Circle K'),
('CBS'),
('ABC'),
('State Bank of India'),
('Corona'),
('Qualcomm'),
('Taco Bell'),
('Delta'),
('BT'),
('Valero'),
('Dunkin'),
('Guerlain'),
('Estée Lauder'),
('Heineken'),
('FIS'),
('AutoZone'),
('Coles'),
('HPE'),
('BAE Systems'),
('Spotify'),
('Discover'),
('Pemex'),
('HCL'),
('Fresenius'),
('O2'),
('Jeep'),
('Nintendo'),
('China Post'),
('Xbox'),
('Lukoil'),
('Whole Foods'),
('Tiffany &amp; Co.'),
('CFLD'),
('SFR'),
('CJ Group'),
('Lego'),
('Unicharm Corp'),
('Mahindra Group'),
('Munich Re'),
('Suning'),
('Tokio Marine'),
('American Airlines'),
('Lenovo'),
('CCCC'),
('Chow Tai Fook'),
('Swisscom'),
('PTT'),
('Pantene'),
('Kia'),
('McKinsey'),
('Carmax'),
('Iberdrola'),
('Pizza Hut'),
('Manulife'),
('Dove'),
('Société Générale'),
('Banco Itaú'),
('Hua Xia Bank'),
('Crédit Mutuel'),
('ADP'),
('Wrigley'),
('Shinhan Financial Group'),
('Sysco'),
('General Dynamics'),
('Clinique'),
('United Airlines'),
('Prudential (US)'),
('BHP'),
('AbbVie'),
('Applied Materials'),
('McKesson'),
('Lloyds Bank'),
('Centene Corporation'),
('Swiss Re'),
('Monster'),
('Crédit Agricole'),
('NatWest'),
('Jio'),
('Budweiser'),
('Mengniu'),
('Mercadona'),
('Centurylink'),
('E.ON'),
('ABB'),
('Zalando'),
('COACH'),
('Micron Technology'),
('Hyatt'),
('KB Financial Group'),
('Rogers'),
('Emirates'),
('Claro'),
('Danaher'),
('The North Face'),
('Express Scripts'),
('ANZ'),
('Daikin'),
('Texas Instruments'),
('Conch'),
('Ross Dress For Less'),
('OCBC Bank'),
('Tide'),
('BD'),
('Geely'),
('AIG'),
('Haidilao'),
('BUICK'),
('Sprite'),
('Bloomberg'),
('New China Life (NCL)'),
('Saint-Gobain'),
('Bayer'),
('McLane'),
('SiriusXM'),
('Cardinal Health'),
('Marshalls'),
('BOE'),
('Electronic Arts'),
('Telia'),
('Indian Oil'),
('BNY Mellon'),
('AmerisourceBergen'),
('Aflac'),
('Safran'),
('LENNAR'),
('Servicenow'),
('Wipro'),
('GS Group'),
('Blackrock'),
('McCain'),
('Sodexo'),
('Yonghui Superstores'),
('CNP Assurances'),
('China Re'),
('Cadillac'),
('China Taiping'),
('Anta'),
('Logan'),
('Emerson Electric'),
('Gatorade'),
('Victoria\'s Secret'),
('La Poste'),
('Bristol-Myers Squibb'),
('Sainsbury\'s'),
('BDO Global'),
('Merck &amp; Co'),
('ASML'),
('Nordea'),
('Garnier'),
('Canadian National Railway'),
('Huggies'),
('D.R. Horton'),
('Fujitsu Group'),
('Abbott'),
('Tim Hortons'),
('Maersk'),
('Gujing Gong Jiu'),
('HBO'),
('Bank of Beijing'),
('Cummins'),
('Omega'),
('Banco do Brasil'),
('Victoria'),
('Pfizer'),
('SABIC'),
('Head &amp; Shoulders'),
('Sompo Japan Nipponkoa'),
('UOB'),
('Edeka'),
('MSCI');

INSERT INTO `mercado_liebre_entregable`.`products` (`title`, `description`, `photo`, `price`, `discount`, `stock`, `brand_id`, `category_id`, `created_at`) VALUES ('Notebook Cx Intel Atom 4gb Ram 64gb Ssd Full Hd 1080p Win 10', 'Producto: Notebook CX 23500w\n\n¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯\n\nCaracterísticas del producto\n• Con Windows 10 - Home y todo el poder de Intel\n• Incluye: Cargador de pared, Manual de usuario y tarjeta de garantía.\nEspecificaciones principales\n• Pantalla: 14.1” – Formato 16:9 - LED/IPS\n• Procesador: Intel Atom x5-Z8350 1.44Ghz\n• Memoria RAM: 4GB DDR3\n• Almacenamiento: 64GB eMMC\n• Gráficos: Intel ®HD Graphics\n• Resolución: 1920 px x 1080 px - FullHD\n• Cámarafrontal: 0.3MP\n• Teclado: Español\n• Batería: Lithium – ion polymer battery 3.7V 9000 mAh\n• Puertos: Mini HDMI Type C 1.4 / x1USB3.0 / x1USB2.0 SoportaSDHC / SDXC\n• Conectividad: WIFI802.11 b/g/n – Bluetooth 4.0\n• Sistema operativo: Windows 10 Home\n• Dimensiones: 328mm x 220mm x 17.8mm\n• Peso: 1.15 kg\n• Color disponible: Blanco\n• Garantía: 12meses\n\n', '/images/products/img-laptop-lenovo.png', '31299', '0', '15', '373', '144', '2020-03-13 14:36:00'),
('Cafetera Moulinex Dolce Gusto Edited', 'Cafetera Dolce Gusto Lumio. La cafetera Dolce Gusto Lumio es de variedad automática que ha llegado con un diseño radical al que nos tenía acostumbrados Dolce Gusto.En este post te contamos todo lo que necesitas saber sobre ella, desde sus características técnicas hasta la calidad de las cápsulas o price.', '/images/products/img-cafetera-moulinex.png', '500', '10', '30', '329', '251', now()),
('Macbook Pro 2022', 'Macbook Pro 2019 Mpxq2ll/a Intel Core i5 2.3 Ghz 8gb RAM 128gb SSD Pantalla 13.3\" Retina Apple Nueva Original. Importada de USA. Se entrega con la factura de compra para contar con la garantía del fabricante.', '/images/products/img-macbook-pro-2019.png', '50000', '7', '150', '1', '134', now()),
('Samsung Galaxy S10', 'Experiencia visual excepcional. Mirá tus series y películas favoritas con la mejor definición.Tendrás colores brillantes y detalles precisos en todos tus contenidos.Disfrutá aún más del mejor entretenimiento gracias a su vasta pantalla y ángulos de visión amplios.', '/images/products/img-samsung-galaxy-s10.png', '72999', '15', '300', '5', '123', now()),
('Heladera no frost Whirlpool WRM45A', 'Disfrutá de la frescura de tus alimentos y almacenalos de manera práctica y cómoda en tu heladera Whirlpool, la protagonista de tu cocina. Su sistema no frost evita la generación de escarcha y te permitirá conservar el sabor y las propiedades nutritivas de los productos.A su vez, su freezer cuenta con una capacidad de 86 litros, que facilitará la distribución y el orden de tus congelados para que no te preocupes por la falta de espacio.', '/images/products/img-heladera-whirpool.png', '47900', '10', '70', '192', '204', now()),
('Nikon Reflex D3500 - Kit', 'Incluye la cámara D3500, el objetivo zoom AF-P DX NIKKOR 18-55mm y el superteleobjetivo zoom compacto AF-P DX NIKKOR 70-300mm. Ambos objetivos enfocan de forma rápida y silenciosa, lo que resulta ideal para grabar metraje de vídeo sin que se escuche apenas el ruido del accionamiento.', '/images/products/img-camara-nikon.png', '53000', '20', '20', '212', '397', now()),
('Aire Acondicionado 3200w Frio / Calor', 'AIRE SPLIT 3200W TACA-3200WCHSA/KC FC TCL. Capacidad frio 3200 Watts. Capacidad calor 3300 Watts. Potencia Electrica(W)frio 996. Potencia Electrica(W)calor 1028. Eficiencia energética calor C. Eficiencia energética frio A. Frigorias 2750 UNIDAD INTERIOR. Peso Bruto 10kg. Peso Neto 7 kg.', '/images/products/img-aire-acondicionado.png', '20999', '12', '10', '204', '204', now()),
('Notebook Lenovo I3 Intel 8gb Ram', 'PROCESADOR / CHIPSET. CPU: Intel Core i3(8a generación) 8130U / 2.2 GHz. Velocidad turbo máxima: 3, 4 GHz. Numero de núcleos: Doble núcleo. Cache: 4 MB. Arquitectura de 64 bit: ss. MEMORIA CACHÉ. Tamaño instalada: 4 MB. ALMACENAMIENTO. Interfaz Serial ATA - 600.', '/images/products/img-laptop-lenovo.png', '36700', '5', '10', '373', '134', now()),
('Apple iPhone 11 Pro Dual SIM 256 GB', '¡El nuevo smartphone que lo tiene todo! Con este lanzamiento, Apple ha superado todos sus récords. Su diseño se destaca por sus líneas finas y distinguidas a partir de una sola hoja de vidrio resistente, combinada con aluminio de excelente calidad.', '/images/products/img-iphone-11.png', '148000', '2', '10', '1', '123', now()),
('Teclado Apple Magic Inalámbrico', 'El teclado mágico combina un diseño elegante con una batería recargable incorporada y funciones clave mejoradas. Con un mecanismo de tijera estable debajo de cada tecla, así como un recorrido de teclas optimizado y un perfil bajo, el Teclado Mágico ofrece una experiencia de escritura notablemente cómoda y precisa.', '/images/products/img-apple-magic-keyboard.png', '11399', '0', '10', '1', '134', now()),
('Mouse Inalámbrico Logitech M280', 'Uso más cómodo para la mano derecha gracias a la forma contorneada con recubrimiento de goma blanda. Duración de las pilas hasta 18 meses, gracias al diseño para ahorrar energía.El M280 entra automáticamente en estado de suspensión cuando no se está usando. Es el mouse que tengo yo Marcelo Fanego en la vida real, y es la posta! Me ayuda mucho a programar ;D', '/images/products/img-mouse-logitech.png', '1500', '10', '100000', '315', '134', now()),
('Parlante Inalámbrico Bose Soundtouch 10', 'Parlante Inalámbrico Bose Soundtouch 10. SoundTouch®.La manera más sencilla de reproducir música en todo su hogar de forma inalámbrica. Características. » Marca: Bose. » Modelo: SoundTouch. » Color: Negro', '/images/products/img-parlante-bose.png', '29990', '12', '1000', '94', '300', now()),
('Home Theatre Sony Bdv-e4100', 'El sonido Surround de 5.1 canales y 1000 W proporciona un audio de verdadero impacto en los efectos especiales de películas y efectos de sonido de música y deportes. Con la tecnología Near Field Communication(NFC) podés disfrutar de Sonido One- Touch para reproducir música de forma instantánea', '/images/products/img-home-theater-sony.png', '32990', '12', '100', '115', '300', now()),
('Smart TV Samsung 4K 50', 'Con el Smart TV Samsung UN50MU6100, viví una nueva experiencia visual con la resolución 4K, que te presentará imágenes con gran detalle y de alta calidad. Ahora todo lo que veas cobrará vida con brillo y colores más reales. Gracias a su tamaño de 50\", podrás transformar tu espacio en una sala de cine y transportarte a donde quieras.', '/images/products/img-tv-samsung-smart.png', '34990', '0', '500', '5', '226', now()),
('Sony S6700 Reproductor De Blu-ray', 'Disfruta de tus películas favoritas con hasta cuatro veces más detalles que Full HD, gracias a la conversión de señales 4K. Cuando se conecta a un televisor compatible,un procesador de video avanzado convierte el video estándar en una señal cercana a la resolución 4K (3840 x 2160). Con ocho millones de píxeles, obtendrás imágenes más nítidas y detalladas, y la mayor calidad de la image te permite sentarte más cerca de la pantalla para que te sientas como en el cine.', '/images/products/img-sony-blueray.png', '10999', '5', '200', '115', '213', now()),
('Bicicleta Mountain Bike Fierce Rodado 29', 'Bicicleta Mountain Bike Fierce Rodado 29 21 velocidades. Tipo: Mountain Bike. Rodado: 29. Material Cuadro: Aluminio. Talle: 18. Suspensión: Delantera. Velocidades: 21 - Shimano. Sistema de Freno: Disco Mecánico. Llantas: Doble pared.', '/images/products/img-bicicleta-fierce.png', '15979', '12', '2000', '34', '70', now()),
('Sony Srs-xb12 Parlante Bluetooth Portátil', 'Deja que la música dance cobre vida con EXTRA BASS™ Anima el ambiente con EXTRA BASS™1. Un radiador pasivo trabaja con el parlante monoaural para potenciar los tonos bajos y mejorar los graves, a pesar del tamaño compacto.', '/images/products/img-parlante-sony.png', '5979', '5', '500', '115', '300', now());